server:
  port: 8080
  servlet.context-path: /demo
# 配置Tomcat编码,默认为UTF-8
  tomcat.uri-encoding: UTF-8
# 配置最大线程数
  tomcat.max-threads: 1000

# 数据库配置
spring:
  datasource:
    # cj是最新的连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 

  jpa:
    hibernate:
      # 这里标记为create代表首次连接的时候会自动根据你的实体类创建数据库表
      ddl-auto: update
    show-sql: true